### ISSUE TITLE
已经修复虎牙播放自动暂停，安装包查看详情

### ISSUE THREAD

**Issue by liuchuancong** [Jackiu1997/hot_live#90]
https://wwvr.lanzouw.com/iC0qQ14xrqob
密码:fipd
[主页](https://github.com/liuchuancong/pure_live)

如果有问题就访问我的主页 pure_live下留言

**Comment by M1NGc** [comment]
列表关注后取消关注  重新打开app   还是关注状态 pc+手机都有这个问题
