### ISSUE TITLE
已修复虎牙直播卡顿,tv播放，添加登录注册，倒计时关闭App以及上传配置文件功能，下载链接点我头像pure_live

### ISSUE THREAD

**Issue by liuchuancong** [Jackiu1997/hot_live#92]
有问题主页留言，不定时更新

**Comment by shadu0** [comment]
倒计时没问题，可画中画小窗没了

**Comment by liuchuancong** [comment]
@shadu0 已经修复安装最新包即可

**Comment by shadu0** [comment]
👍完美，谢谢大佬

**Comment by EkkoY** [comment]
大佬，没有更新pc端吗

> @shadu0 已经修复安装最新包即可

**Comment by liuchuancong** [comment]
> 大佬，没有更新pc端吗

稍等下我打个pc的包
@EkkoY

**Comment by YuI2333** [comment]
感谢大佬！PC端希望能记住窗口位置和大小。

**Comment by liuchuancong** [comment]
@YuI2333 插件包打开会导致白屏 等修复在做这个功能吧，目前windows生态不太完善

**Comment by FadeJay** [comment]
安装pc端的1.1.7版本的包会弹发现新版本v1.1.7的弹窗，实际软件中的版本号是1.1.4，不知道大佬有没有空修复下

**Comment by liuchuancong** [comment]
@FadeJay  windows在重构播放器，可以下载最新版尝试

**Comment by eason27** [comment]
TV版还是1.13吗

**Comment by liuchuancong** [comment]
@eason27 Tv版其实没有多大更改，后面看看能不能使用手机遥控去选择

**Comment by hpkaiq** [comment]
在登陆了账号的情况下，新关注主播，然后不手动点击  我的-上传配置文件，退出 app，再次进入会同步之前的关注的主播，新关注的主播就消失了，所以可以在每次新关注主播后 自动 上传配置文件吗

**Comment by liuchuancong** [comment]
@hpkaiq 对的
